---
name: ifgen
version: "{{major}}.{{minor}}.{{patch}}"
description: An interface generator for distributed computing.
entry: {{entry}}
time_command: true

ci_local:
  - "- uses: seanmiddleditch/gha-setup-ninja@master"
  - "  if: matrix.system == 'ubuntu-latest'"

  - "- run: sudo apt-get install gcc-14 g++-14 clang-19 clang-format-19"
  - "  if: matrix.system == 'ubuntu-latest'"

  - "- run: pip${{'{{matrix.python-version}}'}} install -e ."
  - "- run: pip${{'{{matrix.python-version}}'}} install yambs"
  - "- run: mk python-editable"

requirements:
  - runtimepy>=5.15.0
  - vcorelib>=3.5.9
  - "pytest<8.0.0; sys_platform == 'win32'"

dev_requirements:
  - pytest-cov
  - setuptools-wrapper
  - types-setuptools
  - yambs>=3.0.4

commands:
  - name: gen
    description: generate interfaces
  - name: svd
    description: process CMSIS-SVD files
